services:
  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - "7869:11434"
    volumes:
      - ollama-data:/root/.ollama
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ 'all' ]
              capabilities: [ gpu ]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      OLLAMA_API_URL: http://ollama:11434
    ports:
      - "8000:8000"
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    depends_on:
      - ollama
    volumes:
      - ./:/app

volumes:
  ollama-data: